id: rhcs-brms-install
title: Cloud JBoss BRMS Install Demo
github_repo_url: https://github.com/redhatdemocentral/rhcs-brms-install-demo
technologies:
  - Red Hat CDK
  - JBoss BRMS
  - OpenShift Enterprise  
summary: Project to automate the installation of JBoss BRMS using the Red Hat Container Development Kit (CDK) for application development activities on OpenShift.
level: Beginner
product: rhcs
author: Andrew Block, Eric D. Schabell
